repo: 'typed-ember/glint'
npm: false
github:
  release: true
  releaseName: 'v${version}'
  tokenRef: GITHUB_AUTH
plugins:
  '@release-it-plugins/workspaces': true
  '@release-it-plugins/lerna-changelog': true
