repo: 'typed-ember/glint'
github:
  release: true
  releaseName: 'v${version}'
  tokenRef: GITHUB_AUTH
plugins:
  release-it-yarn-workspaces:
    workspaces:
      - packages/config
      - packages/template
      - packages/transform
      - packages/cli
      - packages/tsserver-plugin
  release-it-lerna-changelog: true
